import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export default StyleSheet.create({
  // ── Layout ────────────────────────────────────────────────────────────────
  container: {
    flex: 1,
    backgroundColor: "#F0F7F6",
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 10,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E8F3F2",
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#0D3B36",
    letterSpacing: -0.5,
  },
  headerSub: {
    fontSize: 12,
    color: "#6B9E99",
    marginTop: 1,
    fontWeight: "500",
  },
  refreshBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#CDEAE7",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0FAF9",
  },

  // ── Search ────────────────────────────────────────────────────────────────
  searchRow: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#E2EFEE",
    paddingHorizontal: 14,
    paddingVertical: 2,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#199A8E",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 11,
    marginLeft: 10,
    color: "#0D3B36",
    fontSize: 14,
    fontWeight: "500",
  },

  // ── Compose card ──────────────────────────────────────────────────────────
  composeCard: {
    marginHorizontal: 16,
    marginTop: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#CDEAE7",
    padding: 16,
    shadowColor: "#199A8E",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  composeHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  composeHeading: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0D3B36",
  },
  anonBadge: {
    backgroundColor: "#F0FAF9",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    alignSelf: "flex-start",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#CDEAE7",
  },
  anonBadgeText: {
    fontSize: 12,
    color: "#199A8E",
    fontWeight: "600",
  },
  composeTitle: {
    borderWidth: 1.5,
    borderColor: "#E2EFEE",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: "#0D3B36",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 10,
    backgroundColor: "#FAFFFE",
  },
  composeContent: {
    borderWidth: 1.5,
    borderColor: "#E2EFEE",
    borderRadius: 12,
    minHeight: 90,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: "#0D3B36",
    fontSize: 14,
    lineHeight: 21,
    backgroundColor: "#FAFFFE",
  },
  postButton: {
    marginTop: 12,
    backgroundColor: "#199A8E",
    borderRadius: 12,
    alignItems: "center",
    paddingVertical: 13,
    shadowColor: "#199A8E",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  postButtonDisabled: {
    backgroundColor: "#A8D5D1",
  },
  postButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 0.2,
  },

  // ── Feed ──────────────────────────────────────────────────────────────────
  loaderWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  loadingText: {
    color: "#6B9E99",
    fontSize: 14,
    fontWeight: "500",
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 120,
  },

  // ── Empty state ───────────────────────────────────────────────────────────
  emptyWrap: {
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: 32,
  },
  emptyEmoji: {
    fontSize: 48,
    marginBottom: 14,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0D3B36",
    marginBottom: 6,
  },
  emptySubText: {
    color: "#6B9E99",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },

  // ── Post card ─────────────────────────────────────────────────────────────
  postCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#E8F3F2",
    padding: 16,
    marginBottom: 12,
    shadowColor: "#199A8E",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 3,
  },
  postHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 10,
  },
  avatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#F0FAF9",
    borderWidth: 1.5,
    borderColor: "#CDEAE7",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarEmoji: {
    fontSize: 18,
  },
  postMeta: {
    flex: 1,
  },
  anonLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0D3B36",
  },
  postTime: {
    fontSize: 11,
    color: "#94A3B8",
    marginTop: 1,
    fontWeight: "500",
  },
  postTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#0D3B36",
    marginBottom: 6,
    lineHeight: 21,
    letterSpacing: -0.2,
  },
  postContent: {
    color: "#475569",
    fontSize: 13.5,
    lineHeight: 20,
    fontWeight: "400",
  },

  // ── Tags ──────────────────────────────────────────────────────────────────
  tagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
  },
  tag: {
    backgroundColor: "#F0FAF9",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: "#CDEAE7",
  },
  tagText: {
    fontSize: 11,
    color: "#199A8E",
    fontWeight: "600",
  },

  // ── Actions ───────────────────────────────────────────────────────────────
  actionsRow: {
    marginTop: 14,
    flexDirection: "row",
    gap: 20,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  actionText: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
  },
  actionTextLiked: {
    color: "#EF4444",
  },

  // ── Comments section ──────────────────────────────────────────────────────
  commentsSection: {
    marginTop: 4,
  },
  commentsDivider: {
    height: 1,
    backgroundColor: "#E8F3F2",
    marginVertical: 12,
  },
  commentBubble: {
    backgroundColor: "#F8FFFE",
    borderRadius: 12,
    padding: 11,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E8F3F2",
  },
  commentAnonLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#199A8E",
    marginBottom: 4,
  },
  commentText: {
    fontSize: 13,
    color: "#475569",
    lineHeight: 19,
  },
  noCommentsText: {
    fontSize: 13,
    color: "#94A3B8",
    textAlign: "center",
    paddingVertical: 12,
    fontStyle: "italic",
  },
  commentInputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    marginTop: 8,
  },
  commentInput: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: "#E2EFEE",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 9,
    color: "#0D3B36",
    fontSize: 13,
    backgroundColor: "#FAFFFE",
    maxHeight: 90,
  },
  sendButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#199A8E",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#199A8E",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  sendButtonDisabled: {
    backgroundColor: "#A8D5D1",
  },

  // ── FAB ───────────────────────────────────────────────────────────────────
  fab: {
    position: "absolute",
    bottom: 80,
    right: 20,
    backgroundColor: "#0D3B36",
    borderRadius: 28,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 13,
    paddingHorizontal: 20,
    gap: 8,
    shadowColor: "#0D3B36",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 8,
  },
  fabText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 0.2,
  },
});