import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1C2A3A",
  },
  refreshBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#CDEAE7",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  searchRow: {
    marginTop: 12,
    marginHorizontal: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    marginLeft: 8,
    color: "#111827",
  },
  composeCard: {
    marginTop: 12,
    marginHorizontal: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 12,
  },
  composeTitle: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: "#111827",
    marginBottom: 8,
  },
  composeContent: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    minHeight: 68,
    textAlignVertical: "top",
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: "#111827",
  },
  postButton: {
    marginTop: 10,
    backgroundColor: "#199A8E",
    borderRadius: 10,
    alignItems: "center",
    paddingVertical: 11,
  },
  postButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  loaderWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 100,
  },
  emptyText: {
    color: "#6B7280",
    textAlign: "center",
    marginTop: 20,
  },
  postCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 12,
    marginBottom: 10,
  },
  postAuthor: {
    fontSize: 12,
    color: "#6B7280",
    marginBottom: 4,
  },
  postTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  postContent: {
    marginTop: 6,
    color: "#374151",
    fontSize: 13,
    lineHeight: 18,
  },
  actionsRow: {
    marginTop: 10,
    flexDirection: "row",
    gap: 16,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  actionText: {
    color: "#6B7280",
    fontSize: 12,
  },
  commentRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  commentInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: "#111827",
  },
  commentButton: {
    backgroundColor: "#199A8E",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  commentButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 12,
  },
  backButton: {
    position: "absolute",
    right: 16,
    bottom: 20,
    backgroundColor: "#1C2A3A",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  backButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
});
