import React, { useState } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  SafeAreaView,
  StyleSheet,
  Alert,
  ActivityIndicator,
  Share,
} from 'react-native';
import {
  ChevronLeft,
  FileText,
  Calendar,
  User,
  Tag,
  Trash2,
  Edit3,
  ClipboardList,
  Brain,
  Pill,
  Stethoscope,
  Activity,
  Download,
} from 'lucide-react-native';
import { deleteMedicalRecord } from '../../services/api';

// ─── Type colour map ──────────────────────────────────────────────────────────
const TYPE_COLOR: Record<string, { bg: string; icon: string }> = {
  'AI Consultation': { bg: '#7C3AED', icon: '#7C3AED' },
  'Appointment':     { bg: '#2563EB', icon: '#2563EB' },
  'Medicine Log':    { bg: '#059669', icon: '#059669' },
  'Mental Wellness': { bg: '#D97706', icon: '#D97706' },
  'Symptom Check':   { bg: '#DB2777', icon: '#DB2777' },
  'Lab Reports':     { bg: '#0284C7', icon: '#0284C7' },
  'Prescriptions':   { bg: '#059669', icon: '#059669' },
  'General':         { bg: '#6B7280', icon: '#6B7280' },
};

function getColor(type: string) {
  return TYPE_COLOR[type] || { bg: '#199A8E', icon: '#199A8E' };
}

function TypeIcon({ type, size = 36, color = '#FFF' }: { type: string; size?: number; color?: string }) {
  switch (type) {
    case 'AI Consultation':  return <Brain size={size} color={color} />;
    case 'Appointment':      return <Stethoscope size={size} color={color} />;
    case 'Medicine Log':     return <Pill size={size} color={color} />;
    case 'Mental Wellness':  return <Activity size={size} color={color} />;
    case 'Symptom Check':    return <ClipboardList size={size} color={color} />;
    default:                 return <FileText size={size} color={color} />;
  }
}

// ─── Source label map ─────────────────────────────────────────────────────────
const SOURCE_LABEL: Record<string, string> = {
  manual:      'Manually Added',
  appointment: 'Auto — Appointment',
  medicine:    'Auto — Medicine Tracker',
  wellness:    'Auto — Mental Wellness',
};

// ─── Download / Share ─────────────────────────────────────────────────────────
async function shareRecord(record: any) {
  const dateStr = new Date(record.record_date || record.createdAt).toDateString();
  const content = [
    '════════════════════════════════',
    '         SEHAT AI HEALTH RECORD',
    '════════════════════════════════',
    `Title        : ${record.title}`,
    `Type         : ${record.record_type}`,
    `Doctor/Source: ${record.doctor_name}`,
    `Date         : ${dateStr}`,
    `Source       : ${SOURCE_LABEL[record.source] || record.source}`,
    '────────────────────────────────',
    'DETAILS',
    '────────────────────────────────',
    record.details?.trim() || 'No additional details recorded.',
    '════════════════════════════════',
    'Generated by Sehat AI',
    new Date().toLocaleString(),
  ].join('\n');

  try {
    await Share.share({ message: content, title: `Sehat AI — ${record.title}` });
  } catch {
    Alert.alert('Error', 'Could not share this record.');
  }
}

// ─── Component ────────────────────────────────────────────────────────────────
export default function MedicalRecordDetailScreen({ route, navigation }: any) {
  const { record } = route.params as { record: any };
  const [deleting, setDeleting] = useState(false);
  const colors = getColor(record.record_type);

  // Parse rawId — only manual records (source = 'manual') have a deletable rawId
  const canDelete = record.canDelete && record.rawId != null;
  const canEdit   = record.canEdit   && record.rawId != null;

  const handleDelete = () => {
    Alert.alert(
      'Delete Record',
      'Are you sure you want to permanently delete this record? This cannot be undone.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            setDeleting(true);
            try {
              await deleteMedicalRecord(record.rawId);
              Alert.alert('Deleted', 'Record removed successfully.', [
                { text: 'OK', onPress: () => navigation.goBack() },
              ]);
            } catch (err: any) {
              Alert.alert('Error', err?.response?.data?.error || 'Could not delete record.');
            } finally {
              setDeleting(false);
            }
          },
        },
      ]
    );
  };

  const detailLines = record.details?.trim()
    ? record.details.trim().split('\n')
    : ['No additional details recorded.'];

  return (
    <View style={styles.root}>
      {/* ── Coloured header ── */}
      <SafeAreaView style={[styles.header, { backgroundColor: colors.bg }]}>
        <View style={styles.headerRow}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
            <ChevronLeft color="#FFF" size={26} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Record Details</Text>

          <View style={styles.headerActions}>
            {/* Download / Share */}
            <TouchableOpacity style={styles.headerIconBtn} onPress={() => shareRecord(record)}>
              <Download color="#FFF" size={18} />
            </TouchableOpacity>

            {/* Edit — only for manual records */}
            {canEdit && (
              <TouchableOpacity
                style={[styles.headerIconBtn, { marginLeft: 8 }]}
                onPress={() => navigation.navigate('AddMedicalRecord', { record })}
              >
                <Edit3 color="#FFF" size={18} />
              </TouchableOpacity>
            )}

            {/* Delete — only for manual records */}
            {canDelete && (
              <TouchableOpacity
                style={[styles.headerIconBtn, { marginLeft: 8 }]}
                onPress={handleDelete}
                disabled={deleting}
              >
                {deleting ? (
                  <ActivityIndicator size="small" color="#FFF" />
                ) : (
                  <Trash2 color="#FFF" size={18} />
                )}
              </TouchableOpacity>
            )}
          </View>
        </View>

        {/* Hero block */}
        <View style={styles.heroBlock}>
          <View style={styles.heroIcon}>
            <TypeIcon type={record.record_type} size={34} color="#FFF" />
          </View>
          <Text style={styles.heroTitle} numberOfLines={2}>{record.title}</Text>
          <View style={styles.heroBadge}>
            <Text style={styles.heroBadgeText}>{record.record_type}</Text>
          </View>
        </View>
      </SafeAreaView>

      {/* ── White sheet ── */}
      <ScrollView
        style={styles.sheet}
        contentContainerStyle={styles.sheetContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Meta cards */}
        <View style={styles.metaGrid}>
          <View style={styles.metaCard}>
            <View style={[styles.metaIconWrap, { backgroundColor: '#E0F2FE' }]}>
              <Calendar size={16} color="#0284C7" />
            </View>
            <Text style={styles.metaLabel}>Date</Text>
            <Text style={styles.metaValue}>
              {new Date(record.record_date || record.createdAt).toDateString()}
            </Text>
          </View>

          <View style={styles.metaCard}>
            <View style={[styles.metaIconWrap, { backgroundColor: '#D1FAE5' }]}>
              <User size={16} color="#059669" />
            </View>
            <Text style={styles.metaLabel}>Doctor / Source</Text>
            <Text style={styles.metaValue} numberOfLines={2}>
              {record.doctor_name || '—'}
            </Text>
          </View>

          <View style={styles.metaCard}>
            <View style={[styles.metaIconWrap, { backgroundColor: '#EDE9FE' }]}>
              <Tag size={16} color="#7C3AED" />
            </View>
            <Text style={styles.metaLabel}>Source</Text>
            <Text style={styles.metaValue}>{SOURCE_LABEL[record.source] || record.source}</Text>
          </View>
        </View>

        {/* Details section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <ClipboardList size={17} color="#199A8E" />
            <Text style={styles.sectionTitle}>Notes & Details</Text>
          </View>
          <View style={styles.detailsBox}>
            {detailLines.map((line: string, i: number) => {
              const isKeyValue = line.includes(':');
              if (isKeyValue) {
                const colonIdx = line.indexOf(':');
                const key = line.slice(0, colonIdx).trim();
                const val = line.slice(colonIdx + 1).trim();
                return (
                  <View key={i} style={styles.detailRow}>
                    <Text style={styles.detailKey}>{key}</Text>
                    <Text style={styles.detailVal}>{val || '—'}</Text>
                  </View>
                );
              }
              return (
                <Text key={i} style={styles.detailPlain}>{line}</Text>
              );
            })}
          </View>
        </View>

        {/* Auto-generated note */}
        {record.source !== 'manual' && (
          <View style={styles.autoNote}>
            <Activity size={14} color="#D97706" />
            <Text style={styles.autoNoteText}>
              This record was auto-generated from your {SOURCE_LABEL[record.source]?.replace('Auto — ', '') || 'health activity'} and cannot be edited.
            </Text>
          </View>
        )}

        {/* Share button */}
        <TouchableOpacity style={styles.shareBtn} onPress={() => shareRecord(record)}>
          <Download size={18} color="#FFF" style={{ marginRight: 8 }} />
          <Text style={styles.shareBtnText}>Share / Download Record</Text>
        </TouchableOpacity>

        {/* Edit button — only for manual */}
        {canEdit && (
          <TouchableOpacity
            style={styles.editBtn}
            onPress={() => navigation.navigate('AddMedicalRecord', { record })}
          >
            <Edit3 size={18} color="#199A8E" style={{ marginRight: 8 }} />
            <Text style={styles.editBtnText}>Edit Record</Text>
          </TouchableOpacity>
        )}
      </ScrollView>
    </View>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F9FAFB' },

  header:    { paddingBottom: 28 },
  headerRow: {
    flexDirection:  'row',
    alignItems:     'center',
    paddingHorizontal: 20,
    paddingTop:     12,
    marginBottom:   20,
  },
  backBtn:    { padding: 4 },
  headerTitle: {
    flex:       1,
    color:      '#FFF',
    fontSize:   18,
    fontWeight: '700',
    marginLeft: 12,
  },
  headerActions: { flexDirection: 'row' },
  headerIconBtn: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius:    8,
    padding:         8,
  },

  heroBlock:  { alignItems: 'center', paddingBottom: 4 },
  heroIcon:   {
    width:           66,
    height:          66,
    borderRadius:    18,
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems:      'center',
    justifyContent:  'center',
    marginBottom:    12,
  },
  heroTitle: {
    color:           '#FFF',
    fontSize:        18,
    fontWeight:      '800',
    textAlign:       'center',
    paddingHorizontal: 24,
    marginBottom:    10,
  },
  heroBadge: {
    backgroundColor: 'rgba(255,255,255,0.25)',
    paddingHorizontal: 16,
    paddingVertical:   5,
    borderRadius:      20,
  },
  heroBadgeText: { color: '#FFF', fontSize: 12, fontWeight: '600' },

  sheet:        {
    flex: 1,
    borderTopLeftRadius:  28,
    borderTopRightRadius: 28,
    marginTop:  -22,
    backgroundColor: '#F9FAFB',
  },
  sheetContent: { padding: 22, paddingBottom: 100 },

  metaGrid: {
    flexDirection: 'row',
    gap:           10,
    marginBottom:  22,
  },
  metaCard: {
    flex:            1,
    backgroundColor: '#FFF',
    borderRadius:    16,
    padding:         12,
    alignItems:      'center',
    shadowColor:     '#000',
    shadowOffset:    { width: 0, height: 1 },
    shadowOpacity:   0.06,
    shadowRadius:    6,
    elevation:       2,
  },
  metaIconWrap: {
    width:          36,
    height:         36,
    borderRadius:   10,
    alignItems:     'center',
    justifyContent: 'center',
    marginBottom:   8,
  },
  metaLabel: { fontSize: 9, color: '#9CA3AF', fontWeight: '600', marginBottom: 4, textAlign: 'center' },
  metaValue: { fontSize: 11, color: '#1F2937', fontWeight: '700', textAlign: 'center' },

  section:       { marginBottom: 20 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems:    'center',
    marginBottom:  10,
    gap:           8,
  },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: '#1F2937' },

  detailsBox: {
    backgroundColor: '#FFF',
    borderRadius:    16,
    padding:         18,
    shadowColor:     '#000',
    shadowOffset:    { width: 0, height: 1 },
    shadowOpacity:   0.06,
    shadowRadius:    6,
    elevation:       2,
  },
  detailRow: {
    flexDirection:  'row',
    alignItems:     'flex-start',
    marginBottom:   10,
    paddingBottom:  10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  detailKey: {
    width:      110,
    fontSize:   12,
    fontWeight: '700',
    color:      '#374151',
  },
  detailVal: {
    flex:       1,
    fontSize:   12,
    color:      '#6B7280',
    lineHeight: 18,
  },
  detailPlain: {
    fontSize:    13,
    color:       '#374151',
    lineHeight:  21,
    marginBottom: 4,
  },

  autoNote: {
    flexDirection:   'row',
    alignItems:      'flex-start',
    backgroundColor: '#FFFBEB',
    borderRadius:    12,
    padding:         14,
    gap:             8,
    marginBottom:    20,
    borderWidth:     1,
    borderColor:     '#FDE68A',
  },
  autoNoteText: {
    flex:       1,
    fontSize:   12,
    color:      '#92400E',
    lineHeight: 18,
  },

  shareBtn: {
    backgroundColor: '#199A8E',
    borderRadius:    16,
    paddingVertical: 15,
    flexDirection:   'row',
    alignItems:      'center',
    justifyContent:  'center',
    marginBottom:    12,
    shadowColor:     '#199A8E',
    shadowOffset:    { width: 0, height: 4 },
    shadowOpacity:   0.3,
    shadowRadius:    8,
    elevation:       6,
  },
  shareBtnText: { color: '#FFF', fontSize: 15, fontWeight: '700' },

  editBtn: {
    backgroundColor: '#F0FDF4',
    borderRadius:    16,
    paddingVertical: 15,
    flexDirection:   'row',
    alignItems:      'center',
    justifyContent:  'center',
    borderWidth:     1.5,
    borderColor:     '#BBF7D0',
  },
  editBtnText: { color: '#199A8E', fontSize: 15, fontWeight: '700' },
});