import React, { useState, useCallback } from 'react';
import {
  SafeAreaView,
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  FlatList,
  ActivityIndicator,
  RefreshControl,
  Share,
  Alert,
  ListRenderItem,
  StyleSheet,
  Dimensions,
} from 'react-native';
import {
  ChevronLeft,
  FileText,
  Download,
  Plus,
  Calendar,
  Brain,
  Pill,
  Stethoscope,
  ClipboardList,
  Activity,
} from 'lucide-react-native';
import { fetchMedicalRecords, getUserProfile } from '../../services/api';
import { getAuth } from '@react-native-firebase/auth';
import { useFocusEffect } from '@react-navigation/native';

// ─── Types ─────────────────────────────────────────────────────────────────────

interface AggregatedRecord {
  id: string;
  rawId: number | null;
  source: 'manual' | 'appointment' | 'medicine' | 'wellness';
  title: string;
  doctor_name: string;
  record_date: string;
  record_type: string;
  details: string;
  color_code: string;
  icon_color: string;
  createdAt: string;
  canEdit: boolean;
  canDelete: boolean;
}

const { width } = Dimensions.get('window');

// ─── Filter config ─────────────────────────────────────────────────────────────
const FILTERS = [
  { label: 'All',             value: 'All' },
  { label: 'AI Consult',      value: 'AI Consultation' },
  { label: 'Appointments',    value: 'Appointment' },
  { label: 'Medicines',       value: 'Medicine Log' },
  { label: 'Mental Wellness', value: 'Mental Wellness' },
  { label: 'Lab Reports',     value: 'Lab Reports' },
  { label: 'Prescriptions',   value: 'Prescriptions' },
  { label: 'General',         value: 'General' },
];

// ─── Icon map ─────────────────────────────────────────────────────────────────
function RecordIcon({ type, color, size = 22 }: { type: string; color: string; size?: number }) {
  switch (type) {
    case 'AI Consultation':  return <Brain size={size} color={color} />;
    case 'Appointment':      return <Stethoscope size={size} color={color} />;
    case 'Medicine Log':     return <Pill size={size} color={color} />;
    case 'Mental Wellness':  return <Activity size={size} color={color} />;
    case 'Symptom Check':    return <ClipboardList size={size} color={color} />;
    default:                 return <FileText size={size} color={color} />;
  }
}

// ─── Download helper ─────────────────────────────────────────────────────────
async function handleDownload(record: AggregatedRecord) {
  const dateStr = new Date(record.record_date || record.createdAt).toDateString();
  const content = [
    '════════════════════════════════',
    '         SEHAT AI HEALTH RECORD',
    '════════════════════════════════',
    `Title        : ${record.title}`,
    `Type         : ${record.record_type}`,
    `Doctor/Source: ${record.doctor_name}`,
    `Date         : ${dateStr}`,
    '────────────────────────────────',
    'DETAILS',
    '────────────────────────────────',
    record.details?.trim() || 'No additional details.',
    '════════════════════════════════',
    'Generated by Sehat AI',
    new Date().toLocaleString(),
  ].join('\n');

  try {
    await Share.share({ message: content, title: record.title });
  } catch (err) {
    Alert.alert('Error', 'Could not share the record.');
  }
}

// ─── Source badge ─────────────────────────────────────────────────────────────
function SourceBadge({ source }: { source: string }) {
  const MAP: Record<string, { label: string; bg: string; text: string }> = {
    manual:      { label: 'Manual',     bg: '#F3F4F6', text: '#6B7280' },
    appointment: { label: 'Appointment',bg: '#DBEAFE', text: '#1D4ED8' },
    medicine:    { label: 'Medicine',   bg: '#D1FAE5', text: '#065F46' },
    wellness:    { label: 'Wellness',   bg: '#FEF3C7', text: '#92400E' },
  };
  const m = MAP[source] || MAP.manual;
  return (
    <View style={[styles.sourceBadge, { backgroundColor: m.bg }]}>
      <Text style={[styles.sourceBadgeText, { color: m.text }]}>{m.label}</Text>
    </View>
  );
}

// ─── Main Screen ──────────────────────────────────────────────────────────────
export default function MedicalRecordsScreen({ navigation }: { navigation: any }) {
  const [records, setRecords]           = useState<AggregatedRecord[]>([]);
  const [loading, setLoading]           = useState(true);
  const [refreshing, setRefreshing]     = useState(false);
  const [selectedFilter, setSelectedFilter] = useState('All');
  const [userId, setUserId]             = useState<number | null>(null);

  // ── Data loading ────────────────────────────────────────────────────────────
  const loadRecords = useCallback(async (showRefresh = false) => {
    if (showRefresh) setRefreshing(true);
    else setLoading(true);

    try {
      const auth = getAuth();
      const firebaseUid = auth.currentUser?.uid;
      if (!firebaseUid) { setRecords([]); return; }

      const profile = await getUserProfile(firebaseUid);
      const uid = profile?.id;
      if (!uid) { setRecords([]); return; }

      setUserId(uid);
      const data: AggregatedRecord[] = await fetchMedicalRecords(uid);
      setRecords(Array.isArray(data) ? data : []);
    } catch (error) {
      console.error('Failed to load records', error);
      Alert.alert('Error', 'Could not load medical records. Please try again.');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useFocusEffect(
    useCallback(() => { loadRecords(); }, [loadRecords])
  );

  // ── Filter logic ────────────────────────────────────────────────────────────
  const filteredRecords =
    selectedFilter === 'All'
      ? records
      : records.filter((r) => r.record_type === selectedFilter);

  // ── Stats ──────────────────────────────────────────────────────────────────
  const totalRecords    = records.length;
  const apptCount       = records.filter((r) => r.source === 'appointment').length;
  const medicineCount   = records.filter((r) => r.source === 'medicine').length;
  const wellnessCount   = records.filter((r) => r.source === 'wellness').length;
  const lastRecord      = records[0];

  // ── Render card ─────────────────────────────────────────────────────────────
  const renderRecordItem: ListRenderItem<AggregatedRecord> = ({ item }) => (
    <TouchableOpacity
      style={styles.recordCard}
      onPress={() => navigation.navigate('MedicalRecordDetail', { record: item })}
      activeOpacity={0.8}
    >
      <View style={[styles.iconBox, { backgroundColor: item.color_code }]}>
        <RecordIcon type={item.record_type} color={item.icon_color} />
      </View>

      <View style={styles.recordInfo}>
        <View style={styles.titleRow}>
          <Text style={styles.recordTitle} numberOfLines={1}>{item.title}</Text>
          {item.canEdit && (
            <View style={styles.editableBadge}>
              <Text style={styles.editableBadgeText}>Editable</Text>
            </View>
          )}
        </View>

        <Text style={styles.doctorName} numberOfLines={1}>{item.doctor_name}</Text>

        <View style={styles.metaRow}>
          <Calendar size={11} color="#9CA3AF" />
          <Text style={styles.dateText}>
            {new Date(item.record_date || item.createdAt).toDateString()}
          </Text>
          <SourceBadge source={item.source} />
        </View>
      </View>

      <TouchableOpacity
        style={styles.downloadIcon}
        onPress={() => handleDownload(item)}
        hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
      >
        <Download size={20} color="#199A8E" />
      </TouchableOpacity>
    </TouchableOpacity>
  );

  // ── Empty state ─────────────────────────────────────────────────────────────
  const EmptyState = () => (
    <View style={styles.emptyContainer}>
      <FileText size={48} color="#D1D5DB" />
      <Text style={styles.emptyTitle}>No records found</Text>
      <Text style={styles.emptySubtext}>
        {selectedFilter === 'All'
          ? 'Your health activities will appear here. Book an appointment, log medicines, or use AI features to build your record.'
          : `No "${selectedFilter}" records yet. Switch to "All" to see everything.`}
      </Text>
      {selectedFilter === 'All' && (
        <View style={styles.emptyActions}>
          <TouchableOpacity
            style={styles.emptyBtn}
            onPress={() => navigation.navigate('AiAssistant')}
          >
            <Text style={styles.emptyBtnText}>AI Consultation</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.emptyBtn, { backgroundColor: '#EDE9FE' }]}
            onPress={() => navigation.navigate('AddMedicalRecord')}
          >
            <Text style={[styles.emptyBtnText, { color: '#7C3AED' }]}>Add Manual Record</Text>
          </TouchableOpacity>
        </View>
      )}
    </View>
  );

  // ── Render ──────────────────────────────────────────────────────────────────
  return (
    <View style={styles.container}>
      {/* ── Header ── */}
      <SafeAreaView>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
            <ChevronLeft color="#FFF" size={28} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Medical Records</Text>
          <TouchableOpacity
            style={styles.addHeaderBtn}
            onPress={() => navigation.navigate('AddMedicalRecord')}
          >
            <Plus color="#FFF" size={22} />
          </TouchableOpacity>
        </View>

        {/* ── Stats grid ── */}
        <View style={styles.statsGrid}>
          <View style={styles.statCard}>
            <Text style={styles.statValue}>{totalRecords}</Text>
            <Text style={styles.statLabel}>Total</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statValue}>{apptCount}</Text>
            <Text style={styles.statLabel}>Appointments</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statValue}>{medicineCount}</Text>
            <Text style={styles.statLabel}>Medicines</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statValue}>{wellnessCount}</Text>
            <Text style={styles.statLabel}>Wellness</Text>
          </View>
        </View>

        {lastRecord && (
          <View style={styles.lastUpdateBar}>
            <Activity size={13} color="#A7F3D0" />
            <Text style={styles.lastUpdateText}>
              Last activity: {new Date(lastRecord.createdAt).toDateString()}
            </Text>
          </View>
        )}
      </SafeAreaView>

      {/* ── Content sheet ── */}
      <View style={styles.contentSheet}>
        {/* ── Filter tabs ── */}
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          style={styles.filtersScroll}
          contentContainerStyle={{ paddingRight: 12 }}
        >
          {FILTERS.map((f) => (
            <TouchableOpacity
              key={f.value}
              style={[styles.filterPill, selectedFilter === f.value && styles.filterPillActive]}
              onPress={() => setSelectedFilter(f.value)}
            >
              <Text style={[styles.filterText, selectedFilter === f.value && styles.filterTextActive]}>
                {f.label}
              </Text>
            </TouchableOpacity>
          ))}
        </ScrollView>

        {/* ── Count indicator ── */}
        <Text style={styles.countText}>
          {filteredRecords.length} record{filteredRecords.length !== 1 ? 's' : ''}
          {selectedFilter !== 'All' ? ` · ${selectedFilter}` : ''}
        </Text>

        {/* ── List ── */}
        {loading ? (
          <View style={styles.loaderContainer}>
            <ActivityIndicator size="large" color="#199A8E" />
            <Text style={styles.loaderText}>Loading your health records…</Text>
          </View>
        ) : (
          <FlatList
            data={filteredRecords}
            keyExtractor={(item) => item.id}
            renderItem={renderRecordItem}
            contentContainerStyle={styles.listContent}
            showsVerticalScrollIndicator={false}
            refreshControl={
              <RefreshControl
                refreshing={refreshing}
                onRefresh={() => loadRecords(true)}
                colors={['#199A8E']}
                tintColor="#199A8E"
              />
            }
            ListEmptyComponent={<EmptyState />}
          />
        )}
      </View>
    </View>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#199A8E',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    marginBottom: 16,
  },
  backButton: { padding: 4 },
  headerTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: '800',
    color: '#FFF',
    marginLeft: 12,
  },
  addHeaderBtn: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 10,
    padding: 8,
  },

  // Stats
  statsGrid: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 10,
    marginBottom: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
  },
  statValue: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: '800',
  },
  statLabel: {
    color: '#A7F3D0',
    fontSize: 10,
    fontWeight: '600',
    marginTop: 2,
    textAlign: 'center',
  },

  lastUpdateBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 16,
    gap: 6,
  },
  lastUpdateText: {
    color: '#A7F3D0',
    fontSize: 12,
    fontWeight: '500',
  },

  // Content sheet
  contentSheet: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 20,
  },

  // Filters
  filtersScroll: {
    flexGrow: 0,
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  filterPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    marginRight: 8,
  },
  filterPillActive: {
    backgroundColor: '#199A8E',
  },
  filterText: {
    color: '#6B7280',
    fontWeight: '500',
    fontSize: 13,
  },
  filterTextActive: {
    color: '#FFF',
    fontWeight: '700',
  },

  countText: {
    fontSize: 12,
    color: '#9CA3AF',
    fontWeight: '500',
    paddingHorizontal: 20,
    marginBottom: 12,
    marginTop: 6,
  },

  // List
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 100,
  },

  // Record card
  recordCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  iconBox: {
    width: 46,
    height: 46,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  recordInfo: { flex: 1 },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 3,
    gap: 6,
  },
  recordTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: '#1F2937',
  },
  editableBadge: {
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  editableBadgeText: {
    fontSize: 9,
    color: '#15803D',
    fontWeight: '600',
  },
  doctorName: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 6,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  dateText: {
    fontSize: 11,
    color: '#9CA3AF',
    flex: 1,
  },

  // Source badge
  sourceBadge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 8,
  },
  sourceBadgeText: {
    fontSize: 9,
    fontWeight: '700',
  },

  downloadIcon: { padding: 8 },

  // Loader
  loaderContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
  },
  loaderText: {
    marginTop: 12,
    color: '#9CA3AF',
    fontSize: 14,
  },

  // Empty
  emptyContainer: {
    alignItems: 'center',
    paddingTop: 40,
    paddingHorizontal: 24,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#374151',
    marginTop: 16,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 13,
    color: '#9CA3AF',
    textAlign: 'center',
    lineHeight: 20,
  },
  emptyActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 20,
  },
  emptyBtn: {
    backgroundColor: '#E0F2FE',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
  },
  emptyBtnText: {
    color: '#0284C7',
    fontWeight: '700',
    fontSize: 13,
  },
});